version: "3.9"
services:
  # Database
  mysql:
    image: mysql:latest
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-p", "user_password"]
      interval: 1m
      timeout: 10s
      retries: 3
    networks:
      - wp_network
  # PHPMyAdmin
  phpmyadmin:
    depends_on:
      - mysql
    build:
      context: ./build/phpmyadmin
      dockerfile: Dockerfile
    volumes:
      - ./phpmyadmin/themes:/var/www/html/themes
    restart: always
    ports:
      - "8080:80"
    env_file: .env
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    networks:
      - wp_network
  # WordPress
  wordpress:
    depends_on:
      - mysql
    build:
      context: ./build/wordpress
      dockerfile: ./Dockerfile
    ports:
      - "8000:80"
    restart: always
    volumes:
      - ./wordpress:/var/www/html
      - ./log/:/var/log
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./error-logging.ini:/usr/local/etc/php/conf.d/error-logging.ini
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: $MYSQL_DATABASE
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DEBUG: 1
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_CONFIG_EXTRA: |
        define('FS_METHOD', 'direct');
        define('SCRIPT_DEBUG', true);
    networks:
      - wp_network
  # WordPress Client
  wpcli:
    depends_on:
      - mysql
      - wordpress
    image: wordpress:cli
    links:
      - mysql:mysql
    volumes_from:
      - wordpress
    entrypoint: wp
    command: "--info"
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: $MYSQL_DATABASE
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DEBUG: 1
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_CONFIG_EXTRA: |
        define('FS_METHOD', 'direct');
    networks:
      - wp_network
networks:
  wp_network:
volumes:
  mysql:
  wordpress:
